[2023-08-12T11:14:29.779+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emrPipeline.create_emr_cluster manual__2023-08-12T11:14:15.088231+00:00 [queued]>
[2023-08-12T11:14:29.788+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emrPipeline.create_emr_cluster manual__2023-08-12T11:14:15.088231+00:00 [queued]>
[2023-08-12T11:14:29.788+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-12T11:14:29.810+0000] {taskinstance.py:1327} INFO - Executing <Task(EmrCreateJobFlowOperator): create_emr_cluster> on 2023-08-12 11:14:15.088231+00:00
[2023-08-12T11:14:29.817+0000] {standard_task_runner.py:57} INFO - Started process 93 to run task
[2023-08-12T11:14:29.821+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'emrPipeline', 'create_emr_cluster', 'manual__2023-08-12T11:14:15.088231+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/emr.py', '--cfg-path', '/tmp/tmpr4rj_56c']
[2023-08-12T11:14:29.824+0000] {standard_task_runner.py:85} INFO - Job 155: Subtask create_emr_cluster
[2023-08-12T11:14:29.841+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-12T11:14:29.888+0000] {task_command.py:410} INFO - Running <TaskInstance: emrPipeline.create_emr_cluster manual__2023-08-12T11:14:15.088231+00:00 [running]> on host 484e6be077e8
[2023-08-12T11:14:29.991+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emrPipeline' AIRFLOW_CTX_TASK_ID='create_emr_cluster' AIRFLOW_CTX_EXECUTION_DATE='2023-08-12T11:14:15.088231+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-12T11:14:15.088231+00:00'
[2023-08-12T11:14:29.992+0000] {emr.py:700} INFO - Creating job flow using aws_conn_id: aws_connection, emr_conn_id: EMR_Connection
[2023-08-12T11:14:30.003+0000] {base.py:73} INFO - Using connection ID 'EMR_Connection' for task execution.
[2023-08-12T11:14:30.015+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-08-12T11:14:30.015+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-08-12T11:14:30.611+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/emr.py", line 708, in execute
    response = self._emr_hook.create_job_flow(job_flow_overrides)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/emr.py", line 134, in create_job_flow
    response = self.get_conn().run_job_flow(**config)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the RunJobFlow operation: User: arn:aws:iam::569280590340:user/paran is not authorized to perform: iam:PassRole on resource: arn:aws:iam::569280590340:role/EMR_DefaultRole with an explicit deny in an identity-based policy
[2023-08-12T11:14:30.621+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=emrPipeline, task_id=create_emr_cluster, execution_date=20230812T111415, start_date=20230812T111429, end_date=20230812T111430
[2023-08-12T11:14:30.633+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 155 for task create_emr_cluster (An error occurred (AccessDeniedException) when calling the RunJobFlow operation: User: arn:aws:iam::569280590340:user/paran is not authorized to perform: iam:PassRole on resource: arn:aws:iam::569280590340:role/EMR_DefaultRole with an explicit deny in an identity-based policy; 93)
[2023-08-12T11:14:30.650+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-12T11:14:30.670+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
