[2023-08-12T20:00:25.291+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-12T20:00:25.351+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: userCase2.validate_file scheduled__2023-08-12T19:00:00+00:00 [queued]>
[2023-08-12T20:00:25.362+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: userCase2.validate_file scheduled__2023-08-12T19:00:00+00:00 [queued]>
[2023-08-12T20:00:25.363+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-12T20:00:25.376+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_file> on 2023-08-12 19:00:00+00:00
[2023-08-12T20:00:25.384+0000] {standard_task_runner.py:57} INFO - Started process 17080 to run task
[2023-08-12T20:00:25.388+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'userCase2', 'validate_file', 'scheduled__2023-08-12T19:00:00+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/userCase.py', '--cfg-path', '/tmp/tmpjkl39txu']
[2023-08-12T20:00:25.391+0000] {standard_task_runner.py:85} INFO - Job 262: Subtask validate_file
[2023-08-12T20:00:25.405+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-12T20:00:25.445+0000] {task_command.py:410} INFO - Running <TaskInstance: userCase2.validate_file scheduled__2023-08-12T19:00:00+00:00 [running]> on host 484e6be077e8
[2023-08-12T20:00:25.457+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-12T20:00:25.531+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='userCase2' AIRFLOW_CTX_TASK_ID='validate_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-12T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-12T19:00:00+00:00'
[2023-08-12T20:00:25.533+0000] {logging_mixin.py:150} INFO - Reading the file
[2023-08-12T20:00:25.551+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2023-08-12T20:00:25.711+0000] {logging_mixin.py:150} INFO - userId,movieId,rating,timestamp
[2023-08-12T20:00:25.711+0000] {logging_mixin.py:150} INFO - 1,31,2.5,1260759144
[2023-08-12T20:00:25.711+0000] {logging_mixin.py:150} INFO - 1,1029,3.0,1260759179
[2023-08-12T20:00:25.711+0000] {logging_mixin.py:150} INFO - 1,1061,3.0,1260759182
[2023-08-12T20:00:25.711+0000] {logging_mixin.py:150} INFO - 1,1129,2.0,1260759185
[2023-08-12T20:00:25.712+0000] {logging_mixin.py:150} INFO - 1,1172,4.0,1260759205
[2023-08-12T20:00:25.712+0000] {logging_mixin.py:150} INFO - 1,1263,2.0,1260759151
[2023-08-12T20:00:25.712+0000] {logging_mixin.py:150} INFO - 1,1287,2.0,1260759187
[2023-08-12T20:00:25.712+0000] {logging_mixin.py:150} INFO - 1,1293,2.0,1260759148
[2023-08-12T20:00:25.712+0000] {logging_mixin.py:150} INFO - 1,1339,3.5,1260759125
[2023-08-12T20:00:25.712+0000] {logging_mixin.py:150} INFO - 1,1343,2.0,1260759131
[2023-08-12T20:00:25.712+0000] {logging_mixin.py:150} INFO - 1,1371,2.5,1260759135
[2023-08-12T20:00:25.713+0000] {logging_mixin.py:150} INFO - 1,1405,1.0,1260759203
[2023-08-12T20:00:25.713+0000] {logging_mixin.py:150} INFO - 1,1953,4.0,1260759191
[2023-08-12T20:00:25.713+0000] {logging_mixin.py:150} INFO - 1,2105,4.0,1260759139
[2023-08-12T20:00:25.713+0000] {logging_mixin.py:150} INFO - 1,2150,3.0,1260759194
[2023-08-12T20:00:25.713+0000] {logging_mixin.py:150} INFO - 1,2193,2.0,1260759198
[2023-08-12T20:00:25.713+0000] {logging_mixin.py:150} INFO - 1,2294,2.0,1260759108
[2023-08-12T20:00:25.714+0000] {logging_mixin.py:150} INFO - 1,2455,2.5,1260759113
[2023-08-12T20:00:25.714+0000] {logging_mixin.py:150} INFO - 1,2968,1.0,1260759200
[2023-08-12T20:00:25.715+0000] {python.py:183} INFO - Done. Returned value was: True
[2023-08-12T20:00:25.742+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=userCase2, task_id=validate_file, execution_date=20230812T190000, start_date=20230812T200025, end_date=20230812T200025
[2023-08-12T20:00:25.765+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-12T20:00:25.796+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
