[2023-08-12T16:50:56.320+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-12T16:50:56.422+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emrPipeline.create_emr_cluster scheduled__2023-08-12T15:00:00+00:00 [queued]>
[2023-08-12T16:50:56.441+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emrPipeline.create_emr_cluster scheduled__2023-08-12T15:00:00+00:00 [queued]>
[2023-08-12T16:50:56.441+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-12T16:50:56.471+0000] {taskinstance.py:1327} INFO - Executing <Task(EmrCreateJobFlowOperator): create_emr_cluster> on 2023-08-12 15:00:00+00:00
[2023-08-12T16:50:56.479+0000] {standard_task_runner.py:57} INFO - Started process 11583 to run task
[2023-08-12T16:50:56.494+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'emrPipeline', 'create_emr_cluster', 'scheduled__2023-08-12T15:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/emr.py', '--cfg-path', '/tmp/tmpyr8ru8qx']
[2023-08-12T16:50:56.497+0000] {standard_task_runner.py:85} INFO - Job 186: Subtask create_emr_cluster
[2023-08-12T16:50:56.519+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-12T16:50:56.572+0000] {task_command.py:410} INFO - Running <TaskInstance: emrPipeline.create_emr_cluster scheduled__2023-08-12T15:00:00+00:00 [running]> on host 484e6be077e8
[2023-08-12T16:50:56.583+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-12T16:50:56.684+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emrPipeline' AIRFLOW_CTX_TASK_ID='create_emr_cluster' AIRFLOW_CTX_EXECUTION_DATE='2023-08-12T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-12T15:00:00+00:00'
[2023-08-12T16:50:56.685+0000] {emr.py:700} INFO - Creating job flow using aws_conn_id: aws_connection, emr_conn_id: EMR_Connection
[2023-08-12T16:50:56.699+0000] {base.py:73} INFO - Using connection ID 'EMR_Connection' for task execution.
[2023-08-12T16:50:56.709+0000] {base.py:73} INFO - Using connection ID 'aws_connection' for task execution.
[2023-08-12T16:50:56.710+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_connection', conn_type='aws') credentials retrieved from login and password.
[2023-08-12T16:50:57.337+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/emr.py", line 708, in execute
    response = self._emr_hook.create_job_flow(job_flow_overrides)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/emr.py", line 134, in create_job_flow
    response = self.get_conn().run_job_flow(**config)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the RunJobFlow operation: Classification 'spark-hive-site' is not valid for parent classification 'spark-env'.
[2023-08-12T16:50:57.346+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=emrPipeline, task_id=create_emr_cluster, execution_date=20230812T150000, start_date=20230812T165056, end_date=20230812T165057
[2023-08-12T16:50:57.359+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 186 for task create_emr_cluster (An error occurred (ValidationException) when calling the RunJobFlow operation: Classification 'spark-hive-site' is not valid for parent classification 'spark-env'.; 11583)
[2023-08-12T16:50:57.379+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-12T16:50:57.417+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
